# Generated by Django 4.2.5 on 2023-09-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_mediafile_alter_endpoint_chainage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_eight', models.CharField(max_length=255, verbose_name='Employee Eight')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEleven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_eleven', models.CharField(max_length=255, verbose_name='Employee Eleven')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFifteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_fiftteen', models.CharField(max_length=255, verbose_name='Employee Fifteen')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_five', models.CharField(max_length=255, verbose_name='Employee Five')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_four', models.CharField(max_length=255, verbose_name='Employee Four')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFourteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_fourteen', models.CharField(max_length=255, verbose_name='Employee Fourteen')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeNine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_nine', models.CharField(max_length=255, verbose_name='Employee Nine')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_seven', models.CharField(max_length=255, verbose_name='Employee Seven')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_six', models.CharField(max_length=255, verbose_name='Employee Six')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ten', models.CharField(max_length=255, verbose_name='Employee Ten')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeThirteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_thirteen', models.CharField(max_length=255, verbose_name='Employee Thirteen')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_three', models.CharField(max_length=255, verbose_name='Employee Three')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTwelve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_twelve', models.CharField(max_length=255, verbose_name='Employee Twelve')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_two', models.CharField(max_length=255, verbose_name='Employee Two')),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.DateField()),
                ('field2', models.CharField(max_length=100)),
                ('field3', models.CharField(max_length=100)),
                ('field4', models.CharField(max_length=100)),
                ('field5', models.CharField(max_length=100)),
                ('field6', models.CharField(max_length=100)),
                ('field7', models.CharField(max_length=100)),
                ('field8', models.CharField(max_length=100)),
                ('field9', models.DateField()),
                ('field10', models.CharField(max_length=100)),
                ('field11', models.CharField(max_length=100)),
                ('field12', models.CharField(max_length=100)),
                ('field13', models.CharField(max_length=100)),
                ('field14', models.CharField(max_length=100)),
                ('field15', models.CharField(max_length=100)),
                ('field16', models.CharField(max_length=100)),
                ('field17', models.CharField(max_length=100)),
                ('field18', models.CharField(max_length=100)),
                ('field19', models.CharField(max_length=100)),
                ('field20', models.CharField(max_length=100)),
                ('field21', models.CharField(max_length=100)),
                ('field22', models.CharField(max_length=100)),
                ('field23', models.CharField(max_length=100)),
                ('field24', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='chainage',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site',
        ),
        migrations.RemoveField(
            model_name='startpoint',
            name='chainage',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='end_point_chainage',
            field=models.PositiveIntegerField(default=0, verbose_name='End Point Chainage'),
        ),
        migrations.AddField(
            model_name='startpoint',
            name='start_point_chainage',
            field=models.PositiveIntegerField(default=0, verbose_name='Start Point Chainage'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='location',
            field=models.URLField(verbose_name='Share a Location (Map)'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='end_point_photos/', verbose_name='Share End Point Photo'),
        ),
        migrations.AlterField(
            model_name='startpoint',
            name='location',
            field=models.URLField(verbose_name='Share a Location (Map)'),
        ),
        migrations.AlterField(
            model_name='startpoint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='start_point_photos/', verbose_name='Share Start Point Photo'),
        ),
    ]
