# Generated by Django 4.2.5 on 2023-10-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_employeeeight_employeeeleven_employeefifteen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery_driver_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinery_driver_name', models.CharField(max_length=255, verbose_name='machinery driver name')),
            ],
        ),
        migrations.AddField(
            model_name='mymodel',
            name='field25',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='field1',
            field=models.CharField(max_length=100),
        ),
    ]
