# Generated by Django 4.2.5 on 2023-10-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_machinery_driver_name_mymodel_field25_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field10',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field11',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field12',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field13',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field14',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field15',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field16',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field17',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field18',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field19',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field20',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field21',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field22',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field23',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field24',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field25',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field4',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field5',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field6',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field7',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field8',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field9',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='activity_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='activity_category'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='activity_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Activity Type'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_eight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Eight'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_eleven',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Eleven'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_fifteen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Fifteen'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_five',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Five'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_four',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Four'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_fourteen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Fourteen'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_nine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Nine'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_one',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee One'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Role'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_seven',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Seven'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_six',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Six'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_ten',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Ten'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_thirteen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Thirteen'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_three',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Three'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_twelve',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Twelve'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='employee_two',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Two'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='end_point_chainage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='End Point Chainage'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='machinery_driver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Machinery Driver Name'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='my_date',
            field=models.DateField(blank=True, null=True, verbose_name='My Date'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='start_point_chainage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Start Point Chainage'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='location',
            field=models.URLField(verbose_name='Share a Location'),
        ),
        migrations.AlterField(
            model_name='startpoint',
            name='location',
            field=models.URLField(verbose_name='Share a Location'),
        ),
    ]
